config/routes.rb
Rails.application.routes.draw do
  resources :feedbacks
  resources :expression_of_interests do
    member do
      get :notify, :approve
    end
  end
  resources :subscription_packs do
    collection do
      get :update_gst_rate_for
    end
  end
  resources :subscriptions do
    member do
      get :notify_expiring
    end
  end
  resources :sponsors
  resources :admins
  resources :admins
  resources :opportunity_school_years
  resources :reports
  resources :engagements do
    member do
      get :invite, :accept, :apply_a_token_to
    end
  end
  resources :engagement_token_packs do
    collection do
      get :update_gst_rate_for
    end
  end
  resources :payments, only: :create
  resources :token_purchases
  resources :opportunity_times
  resources :school_years
  resources :org_users do
    member do
      get :verified_and_admin_approved, :verified_host
    end
  end

  resources :org_user_profiles do
    member do
      get :approve, :prohibit, :resend_register_admin_mailer, :resend_register_user_mailer
    end
  end

  resources :skill_verifications do
    member do
      get :approve
    end
  end
  resources :enquiries
  resources :agreements do
    member do
      get :agree_to
    end
  end
  resources :candidate_types
  resources :opportunity_applications
  resources :opportunities do
    member do
      get :increase_one_token_into,
      :decrease_one_token_from,
      :increase_one_token_into_independent,
      :decrease_one_token_from_independent,
      :status_draft,
      :status_listed,
      :post_active,
      :status_archived,
      :purchase_more_tokens_for,
      :contact_candidate_for,
      :contact_host_for
    end
  end
  resources :organisations do
    member do
      get :remove_host_from, :add_admin_into, :add_host_into, :contact_host_of
    end
  end
  resources :organisation_types
  resources :security_checks do
    member do
      get :verify
    end
  end
  resources :skills do
    member do
      get :add_user, :remove_user, :add_required, :remove_required, :admin_approves_new, :find_opportunities
    end
  end
  resources :skill_categories
  resources :educations do
    member do
      get :verify_candidate
    end
  end
  resources :profiles do
    member do
      get :approve, :prohibit
    end
  end

  get 'admin_page', to: 'pages#admin_page'
  get 'find_organisation', to: 'pages#find_organisation'
  root 'pages#home'
  get 'my_skills', to: 'pages#my_skills'
  get 'thanks', to: 'pages#thanks'
  get 'faqs', to: 'pages#faqs'
  get 'host_profile', to: 'pages#host_profile'
  get 'candidate_profile', to: 'pages#candidate_profile'
  get 'organisations_host', to: 'pages#organisations_host'
  get 'organisations_candidate', to: 'pages#organisations_candidate'
  get 'purchase_tokens', to: 'pages#purchase_tokens'
  get 'required_skills', to: 'pages#required_skills'
  get 'candidate_reports', to: 'pages#candidate_reports'
  get 'admin_candidates', to: 'pages#admin_candidates'
  get 'admin_hosts', to: 'pages#admin_hosts'
  get 'admin_sponsors', to: 'pages#admin_sponsors'
  get 'unverified_education', to: 'pages#unverified_education'
  get 'unverified_wwc', to: 'pages#unverified_wwc'
  get 'independent_host', to: 'pages#independent_host'
  get 'income', to: 'pages#income'
  get 'search_opportunities', to: 'pages#search_opportunities'
  get 'my_roles', to: 'pages#my_roles'
  get 'contact_candidate', to: 'pages#contact_candidate'
  get 'candidate_profile_mini', to: 'pages#candidate_profile_mini'
  get 'become_host_candidate_sponsor', to: 'pages#become_host_candidate_sponsor'
  get 'manual_receipt', to: 'pages#manual_receipt'

  devise_for :users, controllers: { registrations: "registrations" }

end

app/models/skill_category.rb
class SkillCategory < ActiveRecord::Base
	has_many :skills

	default_scope { order name: :asc }

end

app/controllers/skill_categories_controller.rb
class SkillCategoriesController < ApplicationController
  before_action :set_skill_category, only: [:show, :edit, :update, :destroy]
  before_action :check_admin, only: [:index, :show, :new, :edit, :create, :update, :destroy]
  # GET /skill_categories
  # GET /skill_categories.json
  def index
    @skill_categories = SkillCategory.all
  end

  # GET /skill_categories/1
  # GET /skill_categories/1.json
  def show
  end

  # GET /skill_categories/new
  def new
    @skill_category = SkillCategory.new
  end

  # GET /skill_categories/1/edit
  def edit
  end

  # POST /skill_categories
  # POST /skill_categories.json
  def create
    @skill_category = SkillCategory.new(skill_category_params)

    respond_to do |format|
      if @skill_category.save
        format.html { redirect_to @skill_category, notice: 'Skill category was successfully created.' }
        format.json { render :show, status: :created, location: @skill_category }
      else
        format.html { render :new }
        format.json { render json: @skill_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /skill_categories/1
  # PATCH/PUT /skill_categories/1.json
  def update
    respond_to do |format|
      if @skill_category.update(skill_category_params)
        format.html { redirect_to @skill_category, notice: 'Skill category was successfully updated.' }
        format.json { render :show, status: :ok, location: @skill_category }
      else
        format.html { render :edit }
        format.json { render json: @skill_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skill_categories/1
  # DELETE /skill_categories/1.json
  def destroy
    @skill_category.destroy
    respond_to do |format|
      format.html { redirect_to skill_categories_url, notice: 'Skill category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_skill_category
      @skill_category = SkillCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def skill_category_params
      params.require(:skill_category).permit(:name, :description)
    end
end

app/views/skill_categories/_form.html.erb
<%= simple_form_for(@skill_category) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%#= f.input :description %><%# at this stage, do not use description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/skill_categories/edit.html.erb
<div class="row">
	<%= render 'layouts/sidebar' %>
  <div class="col s12 m10 offset-m2 l10 offset-l2">
    <h5>Editing Skill Category</h5>
    <%= render 'form' %>
    <%= link_to 'Back to Listing Skill Categories', skill_categories_path, class: 'btn margin-top-5px' %>
  </div>
</div>

app/views/skill_categories/index.html.erb
<div class="row">
	<%= render 'layouts/sidebar' %>
  <div class="col s12 m10 offset-m2 l10 offset-l2">
    <p id="notice"><%= notice %></p>
    <h5>Listing Approved Skill Categories</h5>
    <%= link_to 'New Skill category', new_skill_category_path, class: 'btn' %>
    <ul class="collapsible" data-collapsible="accordion">
      <% @skill_categories.each do |skill_category| %>
        <li>
          <div class="collapsible-header">
            <i class="material-icons">filter_drama</i><%= skill_category.name %> |
            <%= link_to 'Edit', edit_skill_category_path(skill_category) %> |
            <%= link_to 'Delete', skill_category, method: :delete, data: { confirm: 'Are you sure?' } %>
          </div><%# end if collapsible-header %>

          <div class="collapsible-body">
            <% skill_category.skills.each do |skill| %>
              <% if skill.approved %><%# appears only if admin approved the skill %>
                <!-- <div class='btn-flat'><%#= skill.name %></div> -->
                <%= link_to skill.name, skill_path(skill), class: 'waves-effect waves-teal btn-flat' %>
                <%= link_to 'Edit', edit_skill_path(skill) %> |
                <%= link_to 'Delete', skill, method: :delete, data: { confirm: 'Are you sure?' } %>
                <br>
              <% end %>
            <% end %>
            <%# Add a new other skill: %>
            <div class="row">
              <div class="col s6 offset-s6 m6 offset-m6 l6 offset-l6">
                Add Skill:<br>
                <% @new_skill = Skill.new %>
                <%= simple_form_for(@new_skill) do |f| %>
                  <%= f.error_notification %>
                  <div class="form-inputs">
                    <%= f.association :skill_category, :as => :hidden, input_html: { value: skill_category.id } %>
                    <%= f.input :name, required: true %>
                    <%= f.input :approved, :as => :hidden, input_html: { value: true } %> <%# new skill that is created by the Admin has value 'true'%>
                  </div>
                  <div class="form-actions">
                    <%= f.button :submit %>
                  </div>
                <% end %>
              </div>
            </div>  <%# end of row %>

          </div><%# end if collapsible-body %>

        </li>
      <% end %>
    </ul>
  </div>
</div>
<br>

app/views/skill_categories/new.html.erb
<div class="row">
	<%= render 'layouts/sidebar' %>
  <div class="col s12 m10 offset-m2 l10 offset-l2">
    <h5>New Skill Category</h5>
    <%= render 'form' %>
    <%= link_to 'Back to Listing Skill Categories', skill_categories_path, class: 'btn margin-top-5px' %>
  </div>
</div>

app/views/skill_categories/show.html.erb
<div class="row">
	<%= render 'layouts/sidebar' %>
  <div class="col s12 m10 offset-m2 l10 offset-l2">
    <p id="notice"><%= notice %></p>
    <p>
      <strong>Name:</strong>
      <%= @skill_category.name %>
    </p>

    <!-- <p>
      <strong>Description:</strong>
      <%#= @skill_category.description %>
    </p> -->
    <%= link_to 'Back to Listing Skill Categories', skill_categories_path, class: 'btn margin-top-5px' %>
  </div>
</div>