config/routes.rb
Rails.application.routes.draw do
  resources :feedbacks
  resources :expression_of_interests do
    member do
      get :notify, :approve
    end
  end
  resources :subscription_packs do
    collection do
      get :update_gst_rate_for
    end
  end
  resources :subscriptions do
    member do
      get :notify_expiring
    end
  end
  resources :sponsors
  resources :admins
  resources :admins
  resources :opportunity_school_years
  resources :reports
  resources :engagements do
    member do
      get :invite, :accept, :apply_a_token_to
    end
  end
  resources :engagement_token_packs do
    collection do
      get :update_gst_rate_for
    end
  end
  resources :payments, only: :create
  resources :token_purchases
  resources :opportunity_times
  resources :school_years
  resources :org_users do
    member do
      get :verified_and_admin_approved, :verified_host
    end
  end

  resources :org_user_profiles do
    member do
      get :approve, :prohibit, :resend_register_admin_mailer, :resend_register_user_mailer
    end
  end

  resources :skill_verifications do
    member do
      get :approve
    end
  end
  resources :enquiries
  resources :agreements do
    member do
      get :agree_to
    end
  end
  resources :candidate_types
  resources :opportunity_applications
  resources :opportunities do
    member do
      get :increase_one_token_into,
      :decrease_one_token_from,
      :increase_one_token_into_independent,
      :decrease_one_token_from_independent,
      :status_draft,
      :status_listed,
      :post_active,
      :status_archived,
      :purchase_more_tokens_for,
      :contact_candidate_for,
      :contact_host_for
    end
  end
  resources :organisations do
    member do
      get :remove_host_from, :add_admin_into, :add_host_into, :contact_host_of
    end
  end
  resources :organisation_types
  resources :security_checks do
    member do
      get :verify
    end
  end
  resources :skills do
    member do
      get :add_user, :remove_user, :add_required, :remove_required, :admin_approves_new, :find_opportunities
    end
  end
  resources :skill_categories
  resources :educations do
    member do
      get :verify_candidate
    end
  end
  resources :profiles do
    member do
      get :approve, :prohibit
    end
  end

  get 'admin_page', to: 'pages#admin_page'
  get 'find_organisation', to: 'pages#find_organisation'
  root 'pages#home'
  get 'my_skills', to: 'pages#my_skills'
  get 'thanks', to: 'pages#thanks'
  get 'faqs', to: 'pages#faqs'
  get 'host_profile', to: 'pages#host_profile'
  get 'candidate_profile', to: 'pages#candidate_profile'
  get 'organisations_host', to: 'pages#organisations_host'
  get 'organisations_candidate', to: 'pages#organisations_candidate'
  get 'purchase_tokens', to: 'pages#purchase_tokens'
  get 'required_skills', to: 'pages#required_skills'
  get 'candidate_reports', to: 'pages#candidate_reports'
  get 'admin_candidates', to: 'pages#admin_candidates'
  get 'admin_hosts', to: 'pages#admin_hosts'
  get 'admin_sponsors', to: 'pages#admin_sponsors'
  get 'unverified_education', to: 'pages#unverified_education'
  get 'unverified_wwc', to: 'pages#unverified_wwc'
  get 'independent_host', to: 'pages#independent_host'
  get 'income', to: 'pages#income'
  get 'search_opportunities', to: 'pages#search_opportunities'
  get 'my_roles', to: 'pages#my_roles'
  get 'contact_candidate', to: 'pages#contact_candidate'
  get 'candidate_profile_mini', to: 'pages#candidate_profile_mini'
  get 'become_host_candidate_sponsor', to: 'pages#become_host_candidate_sponsor'
  get 'manual_receipt', to: 'pages#manual_receipt'

  devise_for :users, controllers: { registrations: "registrations" }

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user
  belongs_to :organisation
  validates :user_id, presence: true

  scope :organisation, -> { where('user_type =? OR user_type =?', 'organisation_6_months','organisation_12_months') }
  scope :independent, -> { where(user_type: 'independent') }
  scope :candidate_paid, -> { where('user_type =? OR user_type =?', 'candidate_6_months','candidate_12_months') }
  scope :candidate_volunteer, -> { where('user_type =?', 'candidate_6_months_unpaid') }
  scope :expiring_in_less_than_30_days, -> { where('expiry_date < ?', 30.day.from_now) }
  scope :expiring_in_more_than_30_days, -> { where('expiry_date >= ?', 30.day.from_now) }
  scope :are_active, -> { where('expiry_date >= ?', Date.today) }
  scope :are_expired, -> { where('expiry_date < ?', Date.today) }

  def notified
    !self.notified_at.nil?
  end

  def not_notified
    self.notified_at.nil?
  end

  def active
    self.expiry_date >= Date.today # This is greater and equal than today so that expiry_date that falls on today is still counted as active
  end

  def expired
    self.expiry_date < Date.today # This is less to today so that the expiry date that falls on yesterday or older is inactive
  end

  def expires_in_less_than_30_days
    self.expiry_date < 30.day.from_now
  end

  def expires_in_more_than_30_days
    self.expiry_date >= 30.day.from_now
  end



  # def self.search(search)
	#   where("name ILIKE ? OR suburb ILIKE ? OR state ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
	# end

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:show, :edit, :update, :destroy, :notify_expiring]

  # Must declare in the before_action above, this function will send email to
  def notify_expiring
    SubscriptionMailer.notify(@subscription.id).deliver_now
    @subscription.notified_at = Date.today
    @subscription.save!
    if @subscription.user_type == 'organisation'
      redirect_to subscriptions_path(organisation: 'expiring')
    elsif @subscription.user_type == 'independent'
      redirect_to subscriptions_path(independent: 'expiring')
    elsif @subscription.user_type == 'candidate'
      redirect_to subscriptions_path(candidate: 'expiring')
    end
  end


  # GET /subscriptions
  # GET /subscriptions.json
  def index
    # @subscriptions = Subscription.all

    if params[:organisation] == 'active'
      @subscriptions = Subscription.organisation.expiring_in_more_than_30_days

    elsif params[:organisation] == 'expiring'
      @subscriptions = Subscription.organisation.expiring_in_less_than_30_days.are_active

    elsif params[:organisation] == 'expired'
      @subscriptions = Subscription.organisation.are_expired

    elsif params[:independent] == 'active'
      @subscriptions = Subscription.independent.expiring_in_more_than_30_days

    elsif params[:independent] == 'expiring'
      @subscriptions = Subscription.independent.expiring_in_less_than_30_days.are_active

    elsif params[:independent] == 'expired'
      @subscriptions = Subscription.independent.are_expired

    elsif params[:candidate_paid] == 'active'
      @subscriptions = Subscription.candidate_paid.expiring_in_more_than_30_days

    elsif params[:candidate_paid] == 'expiring'
      @subscriptions = Subscription.candidate_paid.expiring_in_less_than_30_days.are_active

    elsif params[:candidate_paid] == 'expired'
      @subscriptions = Subscription.candidate_paid.are_expired

    elsif params[:candidate_volunteer] == 'active'
      @subscriptions = Subscription.candidate_volunteer.expiring_in_more_than_30_days

    elsif params[:candidate_volunteer] == 'expiring'
      @subscriptions = Subscription.candidate_volunteer.expiring_in_less_than_30_days.are_active

    elsif params[:candidate_volunteer] == 'expired'
      @subscriptions = Subscription.candidate_volunteer.are_expired
    end
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
  end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
    if params[:subscription_pack].present?
      @subscription_pack = SubscriptionPack.find(params[:subscription_pack])
    end
    if params[:org].present?
      @organisation = Organisation.find(params[:org])
    end
  end

  # GET /subscriptions/1/edit
  def edit
    @users = User.all
    @organisations = Organisation.all
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = Subscription.new(subscription_params)
    if @subscription.manual_receipt # this is for manual subscription, token is increased one here in controller.
      if (@subscription.user_type == "organisation_6_months") || (@subscription.user_type == "organisation_12_months")# organisation subscription
        @organisation = Organisation.find(@subscription.organisation_id)
        @organisation.increase_one_token
      elsif @subscription.user_type == "independent"
        @user = User.find(@subscription.user_id)
        @user.org_user_profile.increase_one_token
      end
    end

    # This is to update the unpaid_volunteer attribute to TRUE for unpaid candidate.
    if (@subscription.user_type == "candidate_6_months_unpaid")
      @profile = Profile.find(@subscription.user.profile.id)
      @profile.unpaid_volunteer = true
      @profile.save!
    end

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to @subscription, notice: 'Subscription was successfully created.' }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :new }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscriptions/1
  # PATCH/PUT /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: 'Subscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscription_params
      params.require(:subscription).permit(:user_type, :user_id, :organisation_id, :expiry_date, :payment, :notified_at, :manual_receipt, :notes)
    end
end

app/views/subscriptions/_candidate_subscriptions.html.erb
<%# this is to call the STRIPE PAYMENT PROCESS in controllers/payments_controller.rb file %>
<%= form_tag payments_path(subscription_pack: @subscription_pack.id, user_id: current_user.id) do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span class="font-16px"><b>Amount: <%= number_to_currency(@subscription_pack.price_ex_gst) %></b></span> (excludes GST)
      <br>
      <span class="font-16px"><b>GST: <%= number_to_currency(@subscription_pack.price_ex_gst * @subscription_pack.gst_rate) %></b></span>
      <br>
      <span class="font-16px"><b>Total: <%= number_to_currency(@subscription_pack.price_ex_gst + (@subscription_pack.price_ex_gst * @subscription_pack.gst_rate)) %></b></span>
    </label>
  </article>
  <br>
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-image="<%= asset_path 'MOBEEAS_icon_RGB_350px.png' %>"
    data-name="MOBEEAS"
    data-currency="aud"
    data-email="<%= current_user.email %>"
    data-receipt-email="<%= current_user.email %>"
    data-description="<%= @subscription_pack.name %>"
    data-amount="<%= ((@subscription_pack.price_ex_gst + (@subscription_pack.price_ex_gst * @subscription_pack.gst_rate)) * 100).to_int %>"
    data-locale="auto"></script>
<% end %><%# form_tag %>

app/views/subscriptions/_candidate_unpaid_subscriptions.html.erb
<%= simple_form_for(@subscription) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :user_type, as: :hidden, input_html: { value: 'candidate_6_months_unpaid' } %>
    <%= f.association :user, as: :hidden, input_html: { value: current_user.id } %>
    <%= f.input :expiry_date, as: :hidden, input_html: { value: @last_expiry_date.to_date + 6.months } %>
    <%= f.input :payment, as: :hidden, input_html: { value: 0.00 } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/subscriptions/_form.html.erb
<%= simple_form_for(@subscription) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :user_type, priority: [ "organisation_12_months" ], collection: [ "organisation_12_months", "organisation_6_months", "candidate_12_months", "candidate_6_months", "candidate_6_months_unpaid", "independent"] %>
    <%= f.association :user, collection: @users, label: "Choose a User" %>
    <%= f.association :organisation, collection: @organisations, label: "Select if ORGANISATION Host" %>

    <div class="row">
      <div class="col m6">
        <label for="expiry_date">Expiry Date</label><%# must add * manually because this label is from the <label> tag where * won't appear automatically %>
          <%= f.date_field :expiry_date, as: :string, input_html: { class: 'datetimepicker1' }, placeholder: 'dd/mm/yyyy' %>
        </label>
      </div>
      <div class="col m6">
        <%= f.input :payment, label: "Payment ex. GST" %>
      </div>
    </div>
    <%= f.input :manual_receipt, :as => :hidden, input_html: { value: true } %>
    <%= f.input :notes %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/subscriptions/_independent_subscription.html.erb
<%# this is to call the STRIPE PAYMENT PROCESS in controllers/payments_controller.rb file %>
<%= form_tag payments_path(subscription_pack: @subscription_pack.id, user_id: current_user.id) do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span class="font-16px"><b>Amount: <%= number_to_currency(@subscription_pack.price_ex_gst) %></b></span> (excludes GST)
      <br>
      <span class="font-16px"><b>GST: <%= number_to_currency(@subscription_pack.price_ex_gst * @subscription_pack.gst_rate) %></b></span>
      <br>
      <span class="font-16px"><b>Total: <%= number_to_currency(@subscription_pack.price_ex_gst + (@subscription_pack.price_ex_gst * @subscription_pack.gst_rate)) %></b></span>
    </label>
  </article>
  <br>
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-image="<%= asset_path 'MOBEEAS_icon_RGB_350px.png' %>"
    data-name="MOBEEAS"
    data-currency="aud"
    data-email="<%= current_user.email %>"
    data-receipt-email="<%= current_user.email %>"
    data-description="<%= @subscription_pack.name %>"
    data-amount="<%= ((@subscription_pack.price_ex_gst + (@subscription_pack.price_ex_gst * @subscription_pack.gst_rate)) * 100).to_int %>"
    data-locale="auto"></script>
<% end %><%# form_tag %>

app/views/subscriptions/_org_subscriptions.html.erb
Organisation: <b><%= @organisation.name %></b>.
<br>
<%# this is to call the STRIPE PAYMENT PROCESS in controllers/payments_controller.rb file %>
<%= form_tag payments_path(subscription_pack: @subscription_pack.id, org_id: @organisation.id, user_id: current_user.id) do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span class="font-16px"><b>Amount: <%= number_to_currency(@subscription_pack.price_ex_gst) %></b></span> (excludes GST)
      <br>
      <span class="font-16px"><b>GST: <%= number_to_currency(@subscription_pack.price_ex_gst * @subscription_pack.gst_rate) %></b></span>
      <br>
      <span class="font-16px"><b>Total: <%= number_to_currency(@subscription_pack.price_ex_gst + (@subscription_pack.price_ex_gst * @subscription_pack.gst_rate)) %></b></span>
    </label>
  </article>
  <%#<br>///////publishable_key: %><%#= Rails.configuration.stripe[:publishable_key] %>
  <%#<br>///////secret_key: %><%#= Rails.configuration.stripe[:secret_key] %>
  <br>
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-image="<%= asset_path 'MOBEEAS_icon_RGB_350px.png' %>"
    data-name="MOBEEAS"
    data-currency="aud"
    data-email="<%= current_user.email %>"
    data-receipt-email="<%= current_user.email %>"
    data-description="<%= @subscription_pack.name %>"
    data-amount="<%= ((@subscription_pack.price_ex_gst + (@subscription_pack.price_ex_gst * @subscription_pack.gst_rate)) * 100).to_int %>"
    data-locale="auto"></script>
<% end %><%# form_tag %>

app/views/subscriptions/_subscriptions_list.html.erb
  <tr>
    <td><%= link_to @subscription.id, subscription_path(@subscription.id) %></td>
    <td><%= @subscription.user_type %></td>
    <%# displaying the name of the organisation host, independent host or the candidate %>
    <% if params[:organisation].present? || params[:independent].present? %>
      <td><%= @subscription.user.org_user_profile.name %></td>
    <% elsif (params[:candidate_paid].present?) || (params[:candidate_volunteer].present?) %>
      <td><%= @subscription.user.profile.name %></td>
    <% end %>

    <%# displaying the organisation name for Organisation 6 months subscriptions %>
    <% if params[:organisation].present? %>
      <td><%= @subscription.organisation.name %></td>
    <% end %>
    <td><%= @subscription.expiry_date.getlocal.strftime('%e %b %Y') %></td>
    <td><%= number_to_currency(@subscription.payment) %></td>
    <% if (params[:organisation] == 'expiring') || (params[:independent] == 'expiring') || (params[:candidate_paid] == 'expiring') || (params[:candidate_volunteer] == 'expiring') %>
      <% if @subscription.notified_at.present? %>
        <td><%= @subscription.notified_at.getlocal.strftime('%e %b %Y') %></td>
      <% else %>
        <td>Never</td>
       <% end %>
      <td><%= link_to "Notify", notify_expiring_subscription_path(@subscription)%></td>
    <% end %>

    <%# DO NOT USE THE FUNCTIONS BELOW, KEEP FOR RECORDS ONLY %>
    <%#= link_to 'Show', subscription %>
    <%#= link_to 'Edit', edit_subscription_path(subscription) %>
    <%#= link_to 'Destroy', subscription, method: :delete, data: { confirm: 'Are you sure?' } %>
  </tr>

app/views/subscriptions/edit.html.erb
<h1>Editing Subscription</h1>

<%= render 'form' %>

app/views/subscriptions/index.html.erb
<div class="row">
  <div class="col c12 m9 offset-m1 l9 offset-l1">
    <%= render 'layouts/sidebar' %>
      <p id="notice"><%= notice %></p>

      <% if params[:organisation] == 'active' %>
        <h4>Active Organisation Subscriptions</h4>

      <% elsif params[:organisation] == 'expiring' %>
        <h4>Expiring Organisation Subscriptions</h4>

      <% elsif params[:organisation] == 'expired' %>
        <h4>Expired Organisation Subscriptions</h4>
      <%# =========================================%>

      <% elsif params[:independent] == 'active' %>
        <h4>Active Independent Host Subscriptions</h4>

      <% elsif params[:independent] == 'expiring' %>
        <h4>Expiring Independent Host Subscriptions</h4>

      <% elsif params[:independent] == 'expired' %>
        <h4>Expired Independent Host Subscriptions</h4>
      <%# =========================================%>


      <% elsif params[:candidate_paid] == 'active' %>
        <h4>Active Paid Candidate Subscriptions</h4>

      <% elsif params[:candidate_paid] == 'expiring' %>
        <h4>Expiring Paid Candidate Subscriptions</h4>

      <% elsif params[:candidate_paid] == 'expired' %>
        <h4>Expired Paid Candidate Subscriptions</h4>
        <%# =========================================%>

      <% elsif params[:candidate_volunteer] == 'active' %>
        <h4>Active Volunteer Candidate Subscriptions</h4>

      <% elsif params[:candidate_volunteer] == 'expiring' %>
        <h4>Expiring Volunteer Candidate Subscriptions</h4>

      <% elsif params[:candidate_volunteer] == 'expired' %>
        <h4>Expired Volunteer Candidate Subscriptions</h4>
      <% end %>

      <% if @subscriptions.present? %>
        <table>
          <thead>
            <tr>
              <th>ID</th>
              <th>Type</th>
              <th>User</th>
              <% if params[:organisation].present? %>
                <th>Organisation</th>
              <% end %>
              <th>Expiry</th>
              <th>Payment (ex GST)</th>
              <%# the function to notify the user with expiring subscription is available for all three types of users%>
              <% if (params[:organisation] == 'expiring') || (params[:independent] == 'expiring') || (params[:candidate_paid] == 'expiring') || (params[:candidate_volunteer] == 'expiring')%>
                <th>Notified</th>
                <th>Action</th>
              <% end %>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @subscriptions.order("id ASC").each do |subscription| %>
              <% @subscription = Subscription.find(subscription.id) %><%# set a local variable for partial rendering %>
              <%# for the params 'active', show the subscription if the expiring date more than 30 days in the future %>
              <% if (params[:organisation] == 'active') || (params[:independent] == 'active') || (params[:candidate_paid] == 'active') || (params[:candidate_volunteer] == 'active') %>
                <%# displaying the subscription with expiry date than 30 days in the future %>
                <% if subscription.expires_in_more_than_30_days %>
                  <%= render "subscriptions_list" %>
                <% end %>

              <%# for the params 'expiring', show the subscription if it is still active and expiring in less than 30 days %>
              <% elsif (params[:organisation] == 'expiring') || (params[:independent] == 'expiring') || (params[:candidate_paid] == 'expiring') || (params[:candidate_volunteer] == 'expiring') %>
                <%# displaying the subscription with active status but expiring less than 30 days %>
                <% if (subscription.active) && (subscription.expires_in_less_than_30_days) %>
                  <%= render "subscriptions_list" %>
                <% end %>

              <%# for the params 'expired', show the subscription that has expired %>
              <% elsif (params[:organisation] == 'expired') || (params[:independent] == 'expired') || (params[:candidate_paid] == 'expired') || (params[:candidate_volunteer] == 'expired') %>
                <%# displaying the subscription that has expired %>
                <% if subscription.expired %>
                  <%= render "subscriptions_list" %>
                <% end %>
              <% end %>
            <% end %><%# end of @subscriptions loop %>
          </tbody>
        </table>
      <% else %>
        <% if (params[:organisation]).present? %>
          No organisation subscription available.
        <% elsif (params[:independent]).present? %>
          No independent host subscription available.
        <% elsif (params[:candidate_paid]).present? %>
          No paid candidate subscription available.
        <% elsif (params[:candidate_volunteer]).present? %>
          No volunteer candidate subscription available.
        <% end %>
      <% end %>

      <br>

      <%#= link_to 'New Subscription', new_subscription_path %>
  </div>
</div>

app/views/subscriptions/new.html.erb
<% if (@subscription_pack.name == 'organisation_6_months') || (@subscription_pack.name == 'candidate_6_months') %>
  <h4>New Six Months MOBEEAS Subscription</h4>
<% elsif (@subscription_pack.name == 'candidate_6_months_unpaid') %>
  <h4>Free Six Months MOBEEAS Subscription</h4>
<% else %>
  <h4>New Annual MOBEEAS Subscription</h4>
<% end %>

<p>
  <br>
  <%# this is for ORGANISATION 6 MONTHS subscription ========================== %>
  <% if @subscription_pack.name == 'organisation_6_months' %>
    You are purchasing a 6-month MOBEEAS subscription which includes 1 engagement token.
    <br>
    <%= render 'org_subscriptions' %>

  <%# this is for ORGANISATION 12 MONTHS subscription ========================== %>
  <% elsif @subscription_pack.name == 'organisation_12_months' %>
    You are purchasing a 12-month MOBEEAS subscription which includes 2 engagement tokens.
    <br>
    <%= render 'org_subscriptions' %>

  <%# this is for INDEPENDENT HOST annual subscription ========================== %>
  <% elsif @subscription_pack.name == 'independent' %>
    You are purchasing an annual MOBEEAS subscription which includes 1 engagement token.
    <br>
    <%= render 'independent_subscription' %>

  <%# this is for Candidate 6 MONTHS subscription ========================== %>
  <% elsif @subscription_pack.name == 'candidate_6_months' %>
    You are purchasing a 6-month MOBEEAS subscription for Paid and Unpaid work.
    <br>
    <%= render 'candidate_subscriptions'%>

  <%# this is for Candidate 12 MONTHS subscription ========================== %>
  <% elsif @subscription_pack.name == 'candidate_12_months' %>
    You are purchasing a 12-month MOBEEAS subscription for Paid and Unpaid work.
    <br>
    <%= render 'candidate_subscriptions'%>

  <%# this is for Candidate 6 MONTHS UNPAID VOLUNTEER subscription ========================== %>
  <% elsif @subscription_pack.name == 'candidate_6_months_unpaid' %>
    You are subscribing to a free 6-month MOBEEAS subscription. You will be able to participate in unpaid engagements as an unpaid volunteer.
    <br>
    <% @last_expiry_date = last_subscription(current_user) %>
    <%= render 'candidate_unpaid_subscriptions' %>
    <div class="margin-top-20px">
      <%= link_to "Back to My Profile", candidate_profile_path, class: 'btn' %>
    </div>
  <% end %>
  <br>

  For further payment options, please email <b>mobeeas@mobeeas.com</b>.
  <br><br>
  Secure Payment Service protected by:
  <br>
  <%= cl_image_tag("comodo_secure_seal_100x85_transp.png") %>
</p>

app/views/subscriptions/show.html.erb
<div class="row">
  <div class="col s12 m11 offset-m1 l11 offset-l1">
		<%= render 'layouts/sidebar' %>
    <p id="notice"><%= notice %></p>

    <% if current_user.has_role? :admin %>
      <p>
        <b>User type:</b>
        <%= @subscription.user_type %>
      </p>
    <% end %>

    <% if @subscription.user_type == 'candidate_6_months_unpaid' %>
      <h5>6 Months Unpaid Volunteer Subscription</h5>
    <% end %>

    <p>
      <b>User Email:</b>
      <%= @subscription.user.email %>
    </p>

    <p>
      <% if @subscription.organisation.present? %>
        <b>Organisation:</b>
        <%= @subscription.organisation.name %>
      <% end %>
    </p>

    <p>
      <b>Created date:</b>
      <%= @subscription.created_at.getlocal.strftime('%e %B %Y') %>
    </p>

    <p>
      <b>Expiry date:</b>
      <%= @subscription.expiry_date.getlocal.strftime('%e %B %Y') %>
    </p>

    <p>
      <b>Payment:</b>
      <%= number_to_currency(@subscription.payment) %>
    </p>

    <% if(@subscription.manual_receipt) %>
      <% if @subscription.notes.present? %>
        <p>
          <b>Manual Receipt Notes:</b>
          <%= @subscription.notes %>
        </p>
      <% end %>
    <% end %>
    <% if current_user.has_role? :admin %>
      <%= link_to 'Edit', edit_subscription_path(@subscription) %>
    <% end %>
  </div>
</div>