config/routes.rb
Rails.application.routes.draw do
  resources :feedbacks
  resources :expression_of_interests do
    member do
      get :notify, :approve
    end
  end
  resources :subscription_packs do
    collection do
      get :update_gst_rate_for
    end
  end
  resources :subscriptions do
    member do
      get :notify_expiring
    end
  end
  resources :sponsors
  resources :admins
  resources :admins
  resources :opportunity_school_years
  resources :reports
  resources :engagements do
    member do
      get :invite, :accept, :apply_a_token_to
    end
  end
  resources :engagement_token_packs do
    collection do
      get :update_gst_rate_for
    end
  end
  resources :payments, only: :create
  resources :token_purchases
  resources :opportunity_times
  resources :school_years
  resources :org_users do
    member do
      get :verified_and_admin_approved, :verified_host
    end
  end

  resources :org_user_profiles do
    member do
      get :approve, :prohibit, :resend_register_admin_mailer, :resend_register_user_mailer
    end
  end

  resources :skill_verifications do
    member do
      get :approve
    end
  end
  resources :enquiries
  resources :agreements do
    member do
      get :agree_to
    end
  end
  resources :candidate_types
  resources :opportunity_applications
  resources :opportunities do
    member do
      get :increase_one_token_into,
      :decrease_one_token_from,
      :increase_one_token_into_independent,
      :decrease_one_token_from_independent,
      :status_draft,
      :status_listed,
      :post_active,
      :status_archived,
      :purchase_more_tokens_for,
      :contact_candidate_for,
      :contact_host_for
    end
  end
  resources :organisations do
    member do
      get :remove_host_from, :add_admin_into, :add_host_into, :contact_host_of
    end
  end
  resources :organisation_types
  resources :security_checks do
    member do
      get :verify
    end
  end
  resources :skills do
    member do
      get :add_user, :remove_user, :add_required, :remove_required, :admin_approves_new, :find_opportunities
    end
  end
  resources :skill_categories
  resources :educations do
    member do
      get :verify_candidate
    end
  end
  resources :profiles do
    member do
      get :approve, :prohibit
    end
  end

  get 'admin_page', to: 'pages#admin_page'
  get 'find_organisation', to: 'pages#find_organisation'
  root 'pages#home'
  get 'my_skills', to: 'pages#my_skills'
  get 'thanks', to: 'pages#thanks'
  get 'faqs', to: 'pages#faqs'
  get 'host_profile', to: 'pages#host_profile'
  get 'candidate_profile', to: 'pages#candidate_profile'
  get 'organisations_host', to: 'pages#organisations_host'
  get 'organisations_candidate', to: 'pages#organisations_candidate'
  get 'purchase_tokens', to: 'pages#purchase_tokens'
  get 'required_skills', to: 'pages#required_skills'
  get 'candidate_reports', to: 'pages#candidate_reports'
  get 'admin_candidates', to: 'pages#admin_candidates'
  get 'admin_hosts', to: 'pages#admin_hosts'
  get 'admin_sponsors', to: 'pages#admin_sponsors'
  get 'unverified_education', to: 'pages#unverified_education'
  get 'unverified_wwc', to: 'pages#unverified_wwc'
  get 'independent_host', to: 'pages#independent_host'
  get 'income', to: 'pages#income'
  get 'search_opportunities', to: 'pages#search_opportunities'
  get 'my_roles', to: 'pages#my_roles'
  get 'contact_candidate', to: 'pages#contact_candidate'
  get 'candidate_profile_mini', to: 'pages#candidate_profile_mini'
  get 'become_host_candidate_sponsor', to: 'pages#become_host_candidate_sponsor'
  get 'manual_receipt', to: 'pages#manual_receipt'

  devise_for :users, controllers: { registrations: "registrations" }

end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  belongs_to :user

  mount_uploader :picture, PictureUploader
  
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :set_feedback, only: [:show, :edit, :update, :destroy]

  # GET /feedbacks
  # GET /feedbacks.json
  def index
    @feedbacks = Feedback.all
  end

  # GET /feedbacks/1
  # GET /feedbacks/1.json
  def show
  end

  # GET /feedbacks/new
  def new
    @feedback = Feedback.new
  end

  # GET /feedbacks/1/edit
  def edit
  end

  # POST /feedbacks
  # POST /feedbacks.json
  def create
    @feedback = Feedback.new(feedback_params)

    respond_to do |format|
      if @feedback.save

        format.html { redirect_to thanks_path(type: 'feedback'), notice: 'Feedback was successfully created.' }
        format.json { render :show, status: :created, location: @feedback }
      else
        format.html { render :new }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feedbacks/1
  # PATCH/PUT /feedbacks/1.json
  def update
    respond_to do |format|
      if @feedback.update(feedback_params)
        format.html { redirect_to @feedback, notice: 'Feedback was successfully updated.' }
        format.json { render :show, status: :ok, location: @feedback }
      else
        format.html { render :edit }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1
  # DELETE /feedbacks/1.json
  def destroy
    @feedback.destroy
    respond_to do |format|
      format.html { redirect_to feedbacks_url, notice: 'Feedback was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feedback
      @feedback = Feedback.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feedback_params
      params.require(:feedback).permit(:user_id, :message, :picture)
    end
end

app/views/feedbacks/_form.html.erb
<%= simple_form_for(@feedback) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :user, :as => :hidden, input_html: { value: params[:user_id] } %>
    <%= f.input :message %>
    <%= f.input :picture %>
  </div>
  <br>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/feedbacks/edit.html.erb
<h1>Editing Feedback</h1>

<%= render 'form' %>

<%= link_to 'Show', @feedback %> |
<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/index.html.erb
<div class="row">
  <div class="col s12 m11 offset-m1 l11 offset-l1">
    <%= render 'layouts/sidebar' %>
    <p id="notice"><%= notice %></p>

    <h4>Listing Feedbacks</h4>

    <table>
      <thead>
        <tr>
          <th>User</th>
          <th>Message</th>
          <th>Picture</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @feedbacks.each do |feedback| %>
          <tr>
            <% if feedback.user.has_role? :host %>
              <td><%= link_to feedback.user.id, host_profile_path(viewer: 'admin', org_user_profile_id: feedback.user.org_user_profile.id ) %></td>
            <% elsif feedback.user.has_role? :candidate %>
              <td><%= link_to feedback.user.id, candidate_profile_path(profile_id: feedback.user.profile.id) %></td>
            <% elsif feedback.user.has_role? :sponsor %>
              <td><%= link_to feedback.user.id, sponsor_path(feedback.user.sponsor) %></td>
            <% end %>
            <td><%= feedback.message %></td>
            <% if feedback.picture_url.present? %>
              <td><%= link_to 'Download', feedback.picture_url %></td>
            <% else %>
              <td>None</td>
            <% end %>
            <td><%= link_to 'Show', feedback %></td>
            <td><%= link_to 'Delete', feedback, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

  </div>
</div>

app/views/feedbacks/new.html.erb
<div class="row">
  <div class="col s12 m11 offset-m1 l11 offset-l1">
    <%= render 'layouts/sidebar' %>
    <h4>Your feedback and suggestions are welcome</h4>
    <p>
      Please leave your feedback here.
    </p>
    <%= render 'form' %>
  </div>
</div>

app/views/feedbacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @feedback.user %>
</p>

<p>
  <strong>Message:</strong>
  <%= @feedback.message %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @feedback.picture %>
</p>

<%= link_to 'Edit', edit_feedback_path(@feedback) %> |
<%= link_to 'Back', feedbacks_path %>