config/routes.rb
Rails.application.routes.draw do
  resources :feedbacks
  resources :expression_of_interests do
    member do
      get :notify, :approve
    end
  end
  resources :subscription_packs do
    collection do
      get :update_gst_rate_for
    end
  end
  resources :subscriptions do
    member do
      get :notify_expiring
    end
  end
  resources :sponsors
  resources :admins
  resources :admins
  resources :opportunity_school_years
  resources :reports
  resources :engagements do
    member do
      get :invite, :accept, :apply_a_token_to
    end
  end
  resources :engagement_token_packs do
    collection do
      get :update_gst_rate_for
    end
  end
  resources :payments, only: :create
  resources :token_purchases
  resources :opportunity_times
  resources :school_years
  resources :org_users do
    member do
      get :verified_and_admin_approved, :verified_host
    end
  end

  resources :org_user_profiles do
    member do
      get :approve, :prohibit, :resend_register_admin_mailer, :resend_register_user_mailer
    end
  end

  resources :skill_verifications do
    member do
      get :approve
    end
  end
  resources :enquiries
  resources :agreements do
    member do
      get :agree_to
    end
  end
  resources :candidate_types
  resources :opportunity_applications
  resources :opportunities do
    member do
      get :increase_one_token_into,
      :decrease_one_token_from,
      :increase_one_token_into_independent,
      :decrease_one_token_from_independent,
      :status_draft,
      :status_listed,
      :post_active,
      :status_archived,
      :purchase_more_tokens_for,
      :contact_candidate_for,
      :contact_host_for
    end
  end
  resources :organisations do
    member do
      get :remove_host_from, :add_admin_into, :add_host_into, :contact_host_of
    end
  end
  resources :organisation_types
  resources :security_checks do
    member do
      get :verify
    end
  end
  resources :skills do
    member do
      get :add_user, :remove_user, :add_required, :remove_required, :admin_approves_new, :find_opportunities
    end
  end
  resources :skill_categories
  resources :educations do
    member do
      get :verify_candidate
    end
  end
  resources :profiles do
    member do
      get :approve, :prohibit
    end
  end

  get 'admin_page', to: 'pages#admin_page'
  get 'find_organisation', to: 'pages#find_organisation'
  root 'pages#home'
  get 'my_skills', to: 'pages#my_skills'
  get 'thanks', to: 'pages#thanks'
  get 'faqs', to: 'pages#faqs'
  get 'host_profile', to: 'pages#host_profile'
  get 'candidate_profile', to: 'pages#candidate_profile'
  get 'organisations_host', to: 'pages#organisations_host'
  get 'organisations_candidate', to: 'pages#organisations_candidate'
  get 'purchase_tokens', to: 'pages#purchase_tokens'
  get 'required_skills', to: 'pages#required_skills'
  get 'candidate_reports', to: 'pages#candidate_reports'
  get 'admin_candidates', to: 'pages#admin_candidates'
  get 'admin_hosts', to: 'pages#admin_hosts'
  get 'admin_sponsors', to: 'pages#admin_sponsors'
  get 'unverified_education', to: 'pages#unverified_education'
  get 'unverified_wwc', to: 'pages#unverified_wwc'
  get 'independent_host', to: 'pages#independent_host'
  get 'income', to: 'pages#income'
  get 'search_opportunities', to: 'pages#search_opportunities'
  get 'my_roles', to: 'pages#my_roles'
  get 'contact_candidate', to: 'pages#contact_candidate'
  get 'candidate_profile_mini', to: 'pages#candidate_profile_mini'
  get 'become_host_candidate_sponsor', to: 'pages#become_host_candidate_sponsor'
  get 'manual_receipt', to: 'pages#manual_receipt'

  devise_for :users, controllers: { registrations: "registrations" }

end

app/models/education.rb
class Education < ActiveRecord::Base
  belongs_to :user

  validates :institution, :course, :year_completed, presence: true
  # validates :terms, :acceptance => {:accept => true}, if: :current_enrolment?

  mount_uploader :achievement, PictureUploader

  def current_enrolment?
  	year_completed >= Date.today.year.to_s
  end

  scope :unverified, -> {where(verified: false)}

  def verify
    self.verified = true
    self.save!
  end

end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController
  before_action :set_education, only: [:show, :edit, :update, :destroy, :verify_candidate]
  skip_before_action :check_admin, except: [:index, :show]


  def verify_candidate
    if @education.verify
      EducationMailer.approved_by_admin(@education.id).deliver_now
    end
    redirect_to unverified_education_path
  end

  # GET /educations
  # GET /educations.json
  def index
    @educations = Education.all
  end

  # GET /educations/1
  # GET /educations/1.json
  def show
  end

  # GET /educations/new
  def new
    @education = Education.new
  end

  # GET /educations/1/edit
  def edit

  end

  # POST /educations
  # POST /educations.json
  def create
    @education = Education.new(education_params)
    @education.user = current_user
    respond_to do |format|
      if @education.save
        EducationMailer.notify(@education.id).deliver_now
        format.html { redirect_to profile_path(current_user.profile), notice: 'Education was successfully created.' }
        format.json { render :show, status: :created, location: @education }
      else
        format.html { render :new }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /educations/1
  # PATCH/PUT /educations/1.json
  def update
    respond_to do |format|
      if @education.update(education_params)
        format.html { redirect_to profile_path(current_user.profile), notice: 'Education was successfully updated.' }
        format.json { render :show, status: :ok, location: @education }
      else
        format.html { render :edit }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /educations/1
  # DELETE /educations/1.json
  def destroy
    @education.destroy
    respond_to do |format|
      format.html { redirect_to profile_path(current_user.profile), notice: 'Education was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_education
      @education = Education.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def education_params
      params.require(:education).permit(:terms, :user_id, :institution, :course, :year_completed, :achievement)
    end
end

app/views/educations/_education_terms.html.erb
<input value="0" type="hidden" name="education[terms]" /><input class="boolean optional" type="checkbox" value="1" name="education[terms]" id="education_terms" /><label class="boolean optional checkbox" for="education_terms">I agree to allow MOBEEAS representatives to confirm my enrolment at this educational institution.</label>
  <div class="row"><div class="col m12">

app/views/educations/_form.html.erb
<%= simple_form_for(@education) do |f| %>
  <%= f.error_notification %>
    <%= f.input :institution, label: 'High School/University/College', label_input: { class: 'active'} %>
    <%= f.input :course, label: 'Course/Degree' %>
    <%= f.input :year_completed, label: 'Year completed (past or future)' %>
    <br>
    <div class="row">
      <div class="col s12">
        <%= f.input :achievement %>
        <a href="#modal-achievements" class="modal-trigger"><i class="material-icons">help</i></a>Any files that you upload will be visible to MOBEEAS members.
        <div id="modal-achievements" class="modal">
          <div class="modal-content">
            <p>
              Please upload any evidence of your educational achievements from this institution as a PDF file here.
              <br>
              Please combine multiple transcripts into a single PDF file per institution.
            </p>
          </div>
          <div class="modal-footer">
            <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Close</a>
          </div>
        </div>
      </div>
    </div>

  <% if @education.achievement.present? %>
    <p>Uploaded File:</p>
    <p><%= @education.achievement %></p>
  <% end %>
  <p>By clicking ADD COURSE, I agree to allow MOBEEAS representatives to confirm my enrolment at this educational institution.</p>
  <div class="form-actions margin-top-5px margin-bottom-5px">
    <% if @education.new_record? %>
      <button type="submit" class="btn light-blue">Add course</button>
    <% else %>
      <button type="submit margin-top-5px" class="btn">Update course</button>
    <% end %>
  </div>
  <%= link_to 'Back', candidate_profile_path %>
<% end %>

app/views/educations/edit.html.erb
<div class="card">
	<div class="card-content">
		<h1>Edit your education</h1>
		<%= render 'form' %>
	</div>
</div>

app/views/educations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Educations</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Institution</th>
      <th>Course</th>
      <th>Year completed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @educations.each do |education| %>
      <tr>
        <td><%= education.user %></td>
        <td><%= education.institution %></td>
        <td><%= education.course %></td>
        <td><%= education.year_completed %></td>
        <td><%= link_to 'Show', education %></td>
        <td><%= link_to 'Edit', edit_education_path(education) %></td>
        <td><%= link_to 'Destroy', education, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Education', new_education_path %>

app/views/educations/new.html.erb
<div class="card">
	<div class="card-content">
		<h4>Add your qualifications</h4>
		<%= render 'form' %>
	</div>
</div>

app/views/educations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @education.user %>
</p>

<p>
  <strong>Institution:</strong>
  <%= @education.institution %>
</p>

<p>
  <strong>Course:</strong>
  <%= @education.course %>
</p>

<p>
  <strong>Achievement:</strong>
  <%= @education.achievement %>
</p>


<p>
  <strong>Year completed:</strong>
  <%= @education.year_completed %>
</p>

<%= link_to 'Edit', edit_education_path(@education) %> |
<%= link_to 'Back', educations_path %>